<%= ENV["RAILS_ENV"] %>:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  host: <%= ENV["SHIPIT_HOST"] %>
  redis_url: <%= ENV("REDIS_URL") %>
  github:
    domain: <%= ENV("GITHUB_DOMAIN") %>
    bot_login: <%= ENV("GITHUB_BOT_LOGIN") %>
    app_id: <%= ENV("GITHUB_APP_ID") %>
    installation_id: <%= ENV("GITHUB_INSTALLATION_ID") %>
    webhook_secret: <%= ENV("GITHUB_WEBHOOK_SECRET") %>
    private_key: |
      <%= ENV("GITHUB_PRIVATE_KEY") %>
    oauth:
      id: <%= ENV("GITHUB_OAUTH_ID") %>
      secret: <%= ENV("GITHUB_OAUTH_SECRET") %>
      team: <%= ENV("GITHUB_OAUTH_TEAM") %>
